### ISSUE TITLE
Keyboard in the way of password entry on authentication in dashboard app

### ISSUE THREAD

**Issue by davidhoang** [vizaiapp/VizAISDKRepo#1]
Not a high priority but it took me a second to dismiss and enter the password. In future iterations I might suggest having it in a UIScrollView that will move the form up so the Log In button is in view or having the keyboard "return" key be "Submit"

![photo jan 14 4 58 06 pm](https://user-images.githubusercontent.com/291946/34923004-42ad160c-f94c-11e7-8e91-a15e4b32b21d.png)
Device: iPhone X running iOS 11.2

**Comment by vizaiapp** [comment]
Thank you, David! I added the IQKeyboardManager to the application to handle scrolling up. Will be available in the next version! 👍
